name: .NET Build & Publish

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  schedule:
    - cron: '0 7 * * *'
     
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
        
    - name: Build & DBSvr
      run: |
        cd ./src/DBSvr/
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./DBSvr
        
    - name: Build & LoginSvr
      run: |
        cd ./src/LoginSvr/
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./LoginSvr

    - name: Build & SelGate
      run: |
        cd ./src/SelGate/
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./SelGate
        
    - name: Build & LoginGate
      run: |
        cd ./src/LoginGate/
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./LoginGate
        
    - name: Build & GameSvr
      run: |
        cd ./src/GameSvr/
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./GameSvr
        
    - name: Build & GameGate
      run: |
        cd ./src/GameGate/
        dotnet build --configuration Release --no-restore
        dotnet publish -c Release -o ./GameGate
      
    - name: DBSvr & Zip artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./DBSvr.zip ./DBSvr
        
    - name: LoginSvr & Zip artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./LoginSvr.zip ./LoginSvr
        
    - name: SelGate & Zip artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./SelGate.zip ./SelGate
        
    - name: LoginGate & Zip artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./LoginGate.zip ./LoginGate
        
    - name: GameSvr & Zip artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./GameSvr.zip ./GameSvr
        
    - name: GameGate & Zip artifacts
      uses: montudor/action-zip@v0.1.0
      with:
        args: zip -qq -r ./GameGate.zip ./GameGate
        
    - name: Get release version
      id: version
      uses: ashley-taylor/read-json-property-action@v1.0
      with:
          path: ./version.json
          property: version
          
    - name: Get release description
      id: description
      uses: juliangruber/read-file-action@v1
      with:
        path: ./Changelog.md
        
    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        tag_name: v${{steps.version.outputs.value}}
        release_name: v${{steps.version.outputs.value}}
        body: ${{steps.description.outputs.content}}
        draft: false
        prerelease: false
        
    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./*.zip
        asset_name: dev.${{steps.version.outputs.value}}.zip
        asset_content_type: application/zip
